### ISSUE TITLE
TeslaMate crashed, halting add-on; Cannot index string with string "title"

### ISSUE THREAD

**Issue by swa72** [lildude/ha-addon-teslamate#32]
I've fiddled around with both the PostgresSQL add-on and the Grafana add-on (was working fine with InfluxDB before) but cannot get Teslamate to even start. Anyone any hint?

Log files says ...

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun teslamate (no readiness notification)
s6-rc: info: service legacy-services successfully started
[19:59:34] INFO: Checking for Grafana folder: TeslaMate
jq: error (at <stdin>:1): Cannot index string with string "title"
[20:59:34] ERROR: TeslaMate crashed, halting add-on
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

I start Grafana with 

```
plugins:
  - natel-discrete-panel
  - grafana-googlesheets-datasource
  - grafana-piechart-panel
  - pr0ps-trackmap-panel
  - natel-plotly-panel
custom_plugins:
  - name: panodata-map-panel
    url: >-
      https://github.com/panodata/panodata-map-panel/releases/download/0.16.0/panodata-map-panel-0.16.0.zip
    unsigned: true
env_vars:
  - name: GF_SECURITY_ADMIN_USER
    value: xxx
  - name: GF_SECURITY_ADMIN_PASSWORD
    value: xxx
ssl: true
certfile: fullchain.pem
keyfile: privkey.pem
```

Teslamate starts with ...

```
database_user: yyy
database_pass: yyy
database_name: teslamate
database_host: 29b65938-postgres
database_port: 5432
database_ssl: false
grafana_import_dashboards: true
grafana_folder_name: TeslaMate
grafana_host: a0d7b954-grafana
grafana_port: 3000
grafana_user: xxx
grafana_pass: xxx
disable_mqtt: true
mqtt_host: core-mosquitto
mqtt_user: ""
mqtt_pass: ""
mqtt_tls: false
mqtt_tls_accept_invalid_certs: false
mqtt_namespace: ""
timezone: Europe/London
import_dir: /share/teslamate
default_geofence: ""
encryption_key: 0b28f92c3fe07efa13755c25481c5dd375aade396d03f7d2e861901abc45e29d
env_vars: []
```

**Comment by lildude** [comment]
This will be failing on this command:

https://github.com/lildude/ha-addon-teslamate/blob/2b40dd26688360e3c91f4013fe555ce9c13a47ab/scripts/dashboards.sh#L60-L62

This suggests the call to the Grafana API isn't returning data in the expected format.

Is Grafana definitely running and accessible on port 3000 and accessible by the user you've defined?

What do you get if you SSH into your HA and run (replace `$USER:$PASS` with your configured Grafana username and password):

```console
curl --silent --show-error \
    --user "$USER:$PASS" \
    -H "Content-Type: application/json" \     
    http://a0d7b954-grafana:3000/api/folders
```

**Comment by swa72** [comment]
Thanks for the quick reply. It shows

```
➜  config git:(main) curl --silent --show-error --user "xxx:xxx" -H "Content-Type: application/json" http://a0d7b954-grafana:3000/api/folders 
{"extra":null,"message":"Invalid username or password","messageId":"password-auth.failed","statusCode":401,"traceID":""}
```
Odd, I thought I start Grafana with 

```
env_vars:
  - name: GF_SECURITY_ADMIN_USER
    value: xxx
  - name: GF_SECURITY_ADMIN_PASSWORD
    value: xxx
```

Lets assume, I follow "_Note that the security admin password and usernames can only [...]  or remove the add-on and re-add it._". Will I lose all my dashboard data, etc. or is this stored somewhere in InfluxDB?
